apiVersion: batch/v1
kind: Job
metadata:
  generateName: sender-yaml-
  namespace: test-g-c-p-broker-tracing-from-k-s-v-c-w2fhw
spec:
  backoffLimit: 0
  parallelism: 1
  template:
    spec:
      containers:
      - env:
        - name: BROKER_URL
          value: http://default-brokercell-ingress.cloud-run-events.svc.cluster.local/test-g-c-p-broker-tracing-from-k-s-v-c-w2fhw/gcp-lqoxfvtl
        - name: RETRY
          value: "true"
        image: gcr.io/harwayne2/sender:latest
        imagePullPolicy: Always
        name: sender-ptwadwno
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Never
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

