/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChannelBrokers implements ChannelBrokerInterface
type FakeChannelBrokers struct {
	Fake *FakeInternalV1alpha1
	ns   string
}

var channelbrokersResource = schema.GroupVersionResource{Group: "internal.events.cloud.google.com", Version: "v1alpha1", Resource: "channelbrokers"}

var channelbrokersKind = schema.GroupVersionKind{Group: "internal.events.cloud.google.com", Version: "v1alpha1", Kind: "ChannelBroker"}

// Get takes name of the channelBroker, and returns the corresponding channelBroker object, and an error if there is any.
func (c *FakeChannelBrokers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ChannelBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(channelbrokersResource, c.ns, name), &v1alpha1.ChannelBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelBroker), err
}

// List takes label and field selectors, and returns the list of ChannelBrokers that match those selectors.
func (c *FakeChannelBrokers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ChannelBrokerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(channelbrokersResource, channelbrokersKind, c.ns, opts), &v1alpha1.ChannelBrokerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChannelBrokerList{ListMeta: obj.(*v1alpha1.ChannelBrokerList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChannelBrokerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested channelBrokers.
func (c *FakeChannelBrokers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(channelbrokersResource, c.ns, opts))

}

// Create takes the representation of a channelBroker and creates it.  Returns the server's representation of the channelBroker, and an error, if there is any.
func (c *FakeChannelBrokers) Create(ctx context.Context, channelBroker *v1alpha1.ChannelBroker, opts v1.CreateOptions) (result *v1alpha1.ChannelBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(channelbrokersResource, c.ns, channelBroker), &v1alpha1.ChannelBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelBroker), err
}

// Update takes the representation of a channelBroker and updates it. Returns the server's representation of the channelBroker, and an error, if there is any.
func (c *FakeChannelBrokers) Update(ctx context.Context, channelBroker *v1alpha1.ChannelBroker, opts v1.UpdateOptions) (result *v1alpha1.ChannelBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(channelbrokersResource, c.ns, channelBroker), &v1alpha1.ChannelBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelBroker), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChannelBrokers) UpdateStatus(ctx context.Context, channelBroker *v1alpha1.ChannelBroker, opts v1.UpdateOptions) (*v1alpha1.ChannelBroker, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(channelbrokersResource, "status", c.ns, channelBroker), &v1alpha1.ChannelBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelBroker), err
}

// Delete takes name of the channelBroker and deletes it. Returns an error if one occurs.
func (c *FakeChannelBrokers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(channelbrokersResource, c.ns, name), &v1alpha1.ChannelBroker{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChannelBrokers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(channelbrokersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChannelBrokerList{})
	return err
}

// Patch applies the patch and returns the patched channelBroker.
func (c *FakeChannelBrokers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChannelBroker, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(channelbrokersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChannelBroker{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelBroker), err
}
