/*
Copyright 2020 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"

	v1alpha1 "github.com/google/knative-gcp/pkg/apis/intevents/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeChannelTriggers implements ChannelTriggerInterface
type FakeChannelTriggers struct {
	Fake *FakeInternalV1alpha1
	ns   string
}

var channeltriggersResource = schema.GroupVersionResource{Group: "internal.events.cloud.google.com", Version: "v1alpha1", Resource: "channeltriggers"}

var channeltriggersKind = schema.GroupVersionKind{Group: "internal.events.cloud.google.com", Version: "v1alpha1", Kind: "ChannelTrigger"}

// Get takes name of the channelTrigger, and returns the corresponding channelTrigger object, and an error if there is any.
func (c *FakeChannelTriggers) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.ChannelTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(channeltriggersResource, c.ns, name), &v1alpha1.ChannelTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelTrigger), err
}

// List takes label and field selectors, and returns the list of ChannelTriggers that match those selectors.
func (c *FakeChannelTriggers) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.ChannelTriggerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(channeltriggersResource, channeltriggersKind, c.ns, opts), &v1alpha1.ChannelTriggerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.ChannelTriggerList{ListMeta: obj.(*v1alpha1.ChannelTriggerList).ListMeta}
	for _, item := range obj.(*v1alpha1.ChannelTriggerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested channelTriggers.
func (c *FakeChannelTriggers) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(channeltriggersResource, c.ns, opts))

}

// Create takes the representation of a channelTrigger and creates it.  Returns the server's representation of the channelTrigger, and an error, if there is any.
func (c *FakeChannelTriggers) Create(ctx context.Context, channelTrigger *v1alpha1.ChannelTrigger, opts v1.CreateOptions) (result *v1alpha1.ChannelTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(channeltriggersResource, c.ns, channelTrigger), &v1alpha1.ChannelTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelTrigger), err
}

// Update takes the representation of a channelTrigger and updates it. Returns the server's representation of the channelTrigger, and an error, if there is any.
func (c *FakeChannelTriggers) Update(ctx context.Context, channelTrigger *v1alpha1.ChannelTrigger, opts v1.UpdateOptions) (result *v1alpha1.ChannelTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(channeltriggersResource, c.ns, channelTrigger), &v1alpha1.ChannelTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelTrigger), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeChannelTriggers) UpdateStatus(ctx context.Context, channelTrigger *v1alpha1.ChannelTrigger, opts v1.UpdateOptions) (*v1alpha1.ChannelTrigger, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(channeltriggersResource, "status", c.ns, channelTrigger), &v1alpha1.ChannelTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelTrigger), err
}

// Delete takes name of the channelTrigger and deletes it. Returns an error if one occurs.
func (c *FakeChannelTriggers) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(channeltriggersResource, c.ns, name), &v1alpha1.ChannelTrigger{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeChannelTriggers) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(channeltriggersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.ChannelTriggerList{})
	return err
}

// Patch applies the patch and returns the patched channelTrigger.
func (c *FakeChannelTriggers) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.ChannelTrigger, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(channeltriggersResource, c.ns, name, pt, data, subresources...), &v1alpha1.ChannelTrigger{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.ChannelTrigger), err
}
